/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "grassbg": "#1e241b",
        "grasstxt": "#86a414",
        "poisonbg": "#1d1c2b",
        "poisontxt": "#9f62da",
        "waterbg": "#122227",
        "watertxt": "#36b7d6",
        "firebg": "#2e1b1f",
        "firetxt": "#bc3424",
        "bugbg": "#1F251B",
        "bugtxt": "#829e06",
        "normalbg": "#1E251B",
        "normaltxt": "#4e523e",
        "electricbg": "#27231a",
        "electrictxt": "#ffd500",
        "groundbg": "#24211a",
        "groundtxt": "#4e523e",
        "fairybg": "#2c1d29",
        "fairytxt": "#ed5994",
        "fightingbg": "#24211a",
        "fightingtxt": "#4e523e",
        "psychicbg": "#2c1d29",
        "psychictxt": "#ed5994",
        "rockbg": "#1f251b",
        "rocktxt": "#d98135",
        "ghostbg": "#1c272b",
        "ghosttxt": "#00aeb7",
        "icebg": "#122429",
        "icetxt": "#00f1d2",
        "dragonbg": "#2b1f1c",
        "dragontxt": "#df1644",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
